// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

// Metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Include Google Fonts in metadata (Next.js 15+ supports this)
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="font-geistSans font-geistMono antialiased">
        {children}
      </body>
    </html>
  );
}
